In [1]:
import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV
from sklearn.preprocessing import MinMaxScaler,StandardScaler

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df= pd.read_csv('diabetes (2).csv')
df

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,148,50,35,0,33.6,0.627,50,1
1,85,66,29,0,26.6,0.351,31,0
2,183,64,0,0,23.3,0.672,102,1
3,150,66,23,94,28.1,0.167,21,0
4,150,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...
763,101,76,48,180,32.9,0.171,63,0
764,122,70,27,0,36.8,0.340,27,0
765,121,72,23,112,26.2,0.245,30,0
766,126,60,0,0,30.1,0.349,47,1
767,93,70,31,0,30.4,0.315,23,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Glucose                   768 non-null    int64
 1   BloodPressure             768 non-null    int64
 2   SkinThickness             768 non-null    int64
 3   Insulin                   768 non-null    int64
 4   BMI                       768 non-null    float64
 5   DiabetesPedigreeFunction  768 non-null    float64
 6   Age                       768 non-null    int64
 7   Outcome                   768 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 48.1 KB

In [4]:
df['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [5]:
df.describe()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,121.117188,69.076823,20.536458,79.799479,31.992578,0.471876,33.308594,0.348958
std,31.805091,19.367794,15.952218,115.244002,7.884160,0.331329,11.998145,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,142.000000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,102.000000,1.000000

In [11]:
df['Glucose'].std()

31.805091167178603

In [12]:
df['Glucose'].mean()

121.1171875

# Scaling

In [ ]:
1. Normalization:

In [9]:
x= df.drop('Outcome',axis=1)

normal_scalar= MinMaxScaler()
normal_scalar.fit(x)   # saving min and maximum values

normalized_array=normal_scalar.transform(x)
x_df=pd.DataFrame(normalized_array,columns=x.columns)
x_df

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.743719,0.409836,0.353535,0.000000,0.500745,0.234415,0.358025
1,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,0.123457
2,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,1.000000
3,0.753769,0.540984,0.232323,0.111111,0.418778,0.038002,0.000000
4,0.753769,0.327869,0.353535,0.198582,0.642325,0.943638,0.148148
...,...,...,...,...,...,...,...
763,0.507538,0.622951,0.484848,0.212766,0.490313,0.039710,0.518519
764,0.613065,0.573770,0.272727,0.000000,0.548435,0.111870,0.074074
765,0.608040,0.590164,0.232323,0.132388,0.390462,0.071307,0.111111
766,0.633166,0.491803,0.000000,0.000000,0.448584,0.115713,0.320988
767,0.467337,0.573770,0.313131,0.000000,0.453055,0.101196,0.024691

In [10]:
x_df.describe()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,0.608629,0.566203,0.207439,0.094326,0.476790,0.168179,0.151958
std,0.159825,0.158752,0.161134,0.136222,0.117499,0.141473,0.148125
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.497487,0.508197,0.000000,0.000000,0.406855,0.070773,0.037037
50%,0.587940,0.590164,0.232323,0.036052,0.476900,0.125747,0.098765
75%,0.713568,0.655738,0.323232,0.150414,0.545455,0.234095,0.246914
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
fit  >> Training
fit.transform >> Training
transform>> train,test

In [ ]:
2.standardization:

In [14]:
x= df.drop('Outcome',axis=1)

std_scalar=StandardScaler()  # Saving std and mean values
std_scalar.fit(x)

std_array=std_scalar.transform(x)

x_df1=pd.DataFrame(std_array,columns=x.columns)
x_df1

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.845787,-0.985618,0.907270,-0.692891,0.204013,0.468492,1.392072
1,-1.136319,-0.158966,0.530902,-0.692891,-0.684422,-0.365061,-0.192538
2,1.946957,-0.262298,-1.288212,-0.692891,-1.103255,0.604397,5.728900
3,0.908711,-0.158966,0.154533,0.123302,-0.494043,-0.920763,-1.026543
4,0.908711,-1.502276,0.907270,0.765836,1.409746,5.484909,-0.025737
...,...,...,...,...,...,...,...
763,-0.632927,0.357691,1.722735,0.870031,0.115169,-0.908682,2.476279
764,0.027775,0.047697,0.405445,-0.692891,0.610154,-0.398282,-0.526140
765,-0.003687,0.151028,0.154533,0.279594,-0.735190,-0.685193,-0.275938
766,0.153623,-0.468961,-1.288212,-0.692891,-0.240205,-0.371101,1.141871
767,-0.884623,0.047697,0.656358,-0.692891,-0.202129,-0.473785,-0.859742

In [15]:
x_df1.describe()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,7.680000e+02,7.680000e+02,7.680000e+02,7.680000e+02,7.680000e+02,7.680000e+02,7.680000e+02
mean,-1.647987e-17,-2.563415e-16,7.994184e-17,-3.556183e-17,2.295979e-16,2.398978e-16,-2.659909e-17
std,1.000652e+00,1.000652e+00,1.000652e+00,1.000652e+00,1.000652e+00,1.000652e+00,1.000652e+00
min,-3.810589e+00,-3.568906e+00,-1.288212e+00,-6.928906e-01,-4.060474e+00,-1.189553e+00,-1.026543e+00
25%,-6.958509e-01,-3.656294e-01,-1.288212e+00,-6.928906e-01,-5.955785e-01,-6.889685e-01,-7.763416e-01
50%,-1.295349e-01,1.510282e-01,1.545332e-01,-4.280622e-01,9.419788e-04,-3.001282e-01,-3.593390e-01
75%,6.570150e-01,5.643542e-01,7.190857e-01,4.120079e-01,5.847705e-01,4.662269e-01,6.414674e-01
max,2.450349e+00,2.734316e+00,4.921866e+00,6.652839e+00,4.455807e+00,5.883565e+00,5.728900e+00

# Train Test Split

In [18]:
x= df.drop('Outcome',axis=1)
y= df['Outcome']
x.head()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,148,50,35,0,33.6,0.627,50
1,85,66,29,0,26.6,0.351,31
2,183,64,0,0,23.3,0.672,102
3,150,66,23,94,28.1,0.167,21
4,150,40,35,168,43.1,2.288,33

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=24,stratify=y)

In [21]:
x_test

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
385,119,54,13,50,22.3,0.205,24
397,131,66,40,0,34.3,0.196,22
537,57,60,0,0,21.7,0.735,67
268,102,52,0,0,25.1,0.078,21
244,146,76,35,194,38.2,0.329,29
...,...,...,...,...,...,...,...
75,0,48,20,0,24.7,0.140,22
650,91,54,25,100,25.2,0.234,23
429,95,82,25,180,35.0,0.233,43
594,123,72,45,230,33.6,0.733,34
545,186,90,35,225,34.5,0.423,37

In [22]:
x_train

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
466,74,52,10,36,27.8,0.269,22
669,154,78,30,100,30.9,0.164,45
420,119,88,41,170,45.3,0.507,26
456,135,54,0,0,26.7,0.687,62
750,136,70,0,0,31.2,1.182,22
...,...,...,...,...,...,...,...
381,105,68,22,0,20.0,0.236,22
324,112,75,32,0,35.7,0.148,21
647,179,50,36,159,37.8,0.455,22
704,110,76,20,100,28.4,0.118,27
644,103,72,30,152,27.6,0.730,27

In [ ]:
Model_Training:

In [25]:
knn_clf=KNeighborsClassifier(n_neighbors=5,p=2)
knn_clf.fit(x_train,y_train)

KNeighborsClassifier()

In [26]:
#Evaluation on Testing data:

y_pred=knn_clf.predict(x_test)

cnf_matrix=confusion_matrix(y_test,y_pred)
print('Confusion Matric is:\n',cnf_matrix)

acc_score=accuracy_score(y_test,y_pred)
print("Accuracy:\n",acc_score)

clf_report= classification_report(y_test,y_pred)
print("Classification Report :\n",clf_report)

Confusion Matric is:
 [[96 29]
 [33 34]]
Accuracy:
 0.6770833333333334
Classification Report :
               precision    recall  f1-score   support

           0       0.74      0.77      0.76       125
           1       0.54      0.51      0.52        67

    accuracy                           0.68       192
   macro avg       0.64      0.64      0.64       192
weighted avg       0.67      0.68      0.67       192

In [27]:
#Evaluation on Training data:

y_train_pred=knn_clf.predict(x_train)

cnf_matrix=confusion_matrix(y_train,y_train_pred)
print('Confusion Matric is:\n',cnf_matrix)

acc_score=accuracy_score(y_train,y_train_pred)
print("Accuracy:\n",acc_score)

clf_report= classification_report(y_train,y_train_pred)
print("Classification Report :\n",clf_report)

Confusion Matric is:
 [[334  41]
 [ 67 134]]
Accuracy:
 0.8125
Classification Report :
               precision    recall  f1-score   support

           0       0.83      0.89      0.86       375
           1       0.77      0.67      0.71       201

    accuracy                           0.81       576
   macro avg       0.80      0.78      0.79       576
weighted avg       0.81      0.81      0.81       576

In [ ]:
Hyperparameter Tunning:

In [35]:
knn_clf=KNeighborsClassifier(p=2,n_neighbors=5)

hyperparameters= {'n_neighbors':np.arange(2,30),'p':[1,2]}

gscv_knn_clf= GridSearchCV(knn_clf,hyperparameters,cv=5)
gscv_knn_clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
                         'p': [1, 2]})

In [36]:
gscv_knn_clf.best_estimator_

KNeighborsClassifier(n_neighbors=7)

In [38]:
gscv_knn_clf.best_params_

{'n_neighbors': 7, 'p': 2}

In [37]:
knn_clf=gscv_knn_clf.best_estimator_
knn_clf.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [39]:
#Evaluation on Testing data:

y_pred=knn_clf.predict(x_test)

cnf_matrix=confusion_matrix(y_test,y_pred)
print('Confusion Matric is:\n',cnf_matrix)

acc_score=accuracy_score(y_test,y_pred)
print("Accuracy:\n",acc_score)

clf_report= classification_report(y_test,y_pred)
print("Classification Report :\n",clf_report)

Confusion Matric is:
 [[96 29]
 [34 33]]
Accuracy:
 0.671875
Classification Report :
               precision    recall  f1-score   support

           0       0.74      0.77      0.75       125
           1       0.53      0.49      0.51        67

    accuracy                           0.67       192
   macro avg       0.64      0.63      0.63       192
weighted avg       0.67      0.67      0.67       192

In [40]:
#Evaluation on Training data:

y_train_pred=knn_clf.predict(x_train)

cnf_matrix=confusion_matrix(y_train,y_train_pred)
print('Confusion Matric is:\n',cnf_matrix)

acc_score=accuracy_score(y_train,y_train_pred)
print("Accuracy:\n",acc_score)

clf_report= classification_report(y_train,y_train_pred)
print("Classification Report :\n",clf_report)

Confusion Matric is:
 [[333  42]
 [ 68 133]]
Accuracy:
 0.8090277777777778
Classification Report :
               precision    recall  f1-score   support

           0       0.83      0.89      0.86       375
           1       0.76      0.66      0.71       201

    accuracy                           0.81       576
   macro avg       0.80      0.77      0.78       576
weighted avg       0.81      0.81      0.81       576

In [43]:
import pickle
with open('knn_clf.pkl','wb') as f:
    pickle.dump(knn_clf,f)